### ISSUE TITLE
Urllib 3 connection version

### ISSUE THREAD

**Issue by mfdondanville** [alteia-ai/alteia-python-sdk#1]
In connection.py v1.3, you change from using method_whitelist to allow_method. Allow_method is not fully supported until Urllib 1.26. A requirement of that Urllib version should be a requirement vs the 1.25.10 requirement that is current. Current pip install of Alteia will throw and error: 
packages\alteia\core\connection\connection.py", line 39, in __init__
    'TRACE', 'POST']))
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

**Comment by tducret** [comment]
Hello @mfdondanville,
Sorry about that. `allow_method` is the new parameter for `urllib3` >= 1.26. You must have a previous version already installed.
`alteia 1.3.1` package has just been updated to require this dependency.
Please upgrade with `pip install -U alteia`.
